language: go
go:
  - 1.11.x
install: true
os:
  - linux
dist:
  - xenial
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.11
    - GO111MODULE=on

script:
  - go get -t -v
  - gox -os="linux darwin windows" -arch="amd64" -verbose
  - gox -os="linux darwin windows" -arch="386" -verbose

before_deploy:
  - git config --local user.name "gencebay"
  - git config --local user.email "gencebay.demir@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: ixQPehGZq0hYS+yipgl9bfrhekNAs4isn2hpT7ab3fAuIF0O+5JAlso1+1MfH5Pct0MZ2p72lu8tVJ+AdfLcaNGxdPC71Xv/eWmHheUWIzm3gj9Pe4GFvuxITqOY71I1RS4rMJeZTKdQ8EtN2+hcwdkaNRhVbzZO7pat3ewIiWsbLsao53r9yh6uT+coIY9JSXg10Srdtf2Xfxcd/KqFbMrpGLRWaF7bsfdELbNEfHgjUWvsWolXvm99F9z94pxtaPBG6+0hxPt9j6X5hUTia4F/xuNDXGi+9Brw67CQARzqIxjdDfgqCkK9wr+/oYcbnccymAy53Td0nMGbuhxbVTlyq8MJhDA0aIHn9ly/raastOScXZVgmIhigl9Mj/gP3nZDUfcRUyU1VpVlphOzVSGh20kiBoELGYnr8nwBElI27Jb9kPx5OoUsqU8SUOJ00CLu+71NlfFSLKWMIqrGEPA2oDEEg0XOgstsY1PAK0Dqc4/tfxZs+59Q7/IP/7mJVtDPw0602F66+CoIEedfKCwgLvNusPqPz5zr+HbKlQb7RY5zHF8wmIo7qWxKO8leR/8zdKfua662xiPbAcUIOcM+tgbnfPrEiCGRTRccpmIb4MTKCJb1SUyo2yA9U/gbuJllTb+nuJ4RZyv/du0A8mldUR0PsF8E71lI07bTIUo=
  file_glob: true
  file:
    - "httplive_*"
  skip_cleanup: true
  on:
    repo: gencebay/httplive
